# ✅ Isso pode ir pro GitHub
spring.application.name=tessiebooks
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Variáveis de ambiente (sem valores fixos)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}